---
# facts-recipes file for revboot.openwrt
# Generates feature selection for the build process.

- name: "Facts | Recipes | Initialize variables"
  set_fact:
    openwrt_recipes_yaml: []
    openwrt_recipes_dicts: []
    openwrt_features_add: []
    openwrt_features_del: []
  delegate_to: localhost

- name: "Facts | Recipes | Prepare recipe dictionaries"
  block:
  - name: "Facts | Recipes | Import recipe yaml files"
    set_fact:
      openwrt_recipes_yaml: "{{ openwrt_recipes_yaml | default([]) |
                                combine([ item ]) }}"
    loop:
      - "{{ lookup('file', 'recipes/default.yml')  | from_yaml | trim }}"
      - "{{ lookup('file', 'recipes/minimal.yml')  | from_yaml | trim }}"
      - "{{ lookup('file', 'recipes/extended.yml') | from_yaml | trim }}"
    loop_control:
      index_var: "item_index"
      label: "{{ item_index }}"
  - name: "Facts | Recipes | Prepare recipe dictionaries from yaml import"
    set_fact:
      openwrt_recipes_dicts: "{{ openwrt_recipes_dicts | default([]) |
                                 combine([ item.value ]) }}"
    loop: "{{ openwrt_recipes_yaml | dict2items }}"
    loop_control:
      label: "{{ item.key }}"
  delegate_to: localhost

- name: "Facts | Recipes | Prepare list of features to add/del"
  block:
  - name: "Facts | Recipes | Prepare list of features to add"
    set_fact:
      openwrt_features_add: "{{ openwrt_features_add | default([]) +
                                [ item.1 ] }}"
    with_subelements:
      - "{{ openwrt_recipes_dicts | dict2items }}"
      - value.features_add
    when:
      - openwrt_software['recipe'] is defined
      - openwrt_software['recipe'] == item.0.key
      - item.1 | length > 0
  - name: "Facts | Recipes | Merge list of features to add (recipes + custom)"
    set_fact:
      openwrt_features_add: "{{ openwrt_features_add | default([]) +
                                openwrt_software['features_add'] }}"
    when:
      - openwrt_software['features_add'] is defined
      - openwrt_software['features_add'] | length > 0
  - name: "Facts | Recipes | Prepare list of features to del"
    set_fact:
      openwrt_features_del: "{{ openwrt_features_del | default([]) +
                                [ item.1 ] }}"
    with_subelements:
      - "{{ openwrt_recipes_dicts | dict2items }}"
      - value.features_del
    when:
      - openwrt_software['recipe'] is defined
      - openwrt_software['recipe'] == item.0.key
      - item.1 | length > 0
  - name: "Facts | Recipes | Merge list of features to del (recipes + custom)"
    set_fact:
      openwrt_features_del: "{{ openwrt_features_del | default([]) +
                                openwrt_software['features_del'] }}"
    when:
      - openwrt_software['features_del'] is defined
      - openwrt_software['features_del'] | length > 0
  delegate_to: localhost

- name: "Facts | Recipes | Output recipes vars"
  debug:
    msg:
      - "openwrt_features_add:"
      - "{{ openwrt_features_add | default([]) }}"
      - "openwrt_features_del:"
      - "{{ openwrt_features_del | default([]) }}"
  delegate_to: localhost
