---
# tasks file for revboot.openwrt

- name: "Facts"
  include_tasks: facts.yml

- name: "Download"
  include_tasks: download.yml
  when:
    - "'download' in openwrt_action"

- name: "Facts | Recipes"
  include_tasks: facts-recipes.yml
  when:
    - "'build' in openwrt_action"

- name: "Facts | Features"
  include_tasks: facts-features.yml
  when:
    - "'build' in openwrt_action"

- name: "Make | Clean"
  include_tasks: make-clean.yml
  when:
    - "'clean' in openwrt_action"

- name: "Make | Files"
  include_tasks: make-files.yml
  when:
    - "'build' in openwrt_action"

- name: "Make | Image"
  include_tasks: make-image.yml
  when:
    - "'build' in openwrt_action"

- name: "Flash | Sysupgrade"
  include_tasks: flash-sysupgrade.yml
  when:
    - "'flash-sysupgrade' in openwrt_action"

- name: "Reset | Soft"
  include_tasks: reset-soft.yml
  when:
    - "'reset-soft' in openwrt_action"

- name: "Reset | Hard"
  include_tasks: reset-hard.yml
  when:
    - "'reset-hard' in openwrt_action"
