---
# tasks file for revboot.openwrt

- name: "Facts"
  include_tasks: facts.yml

- name: "Download"
  include_tasks: download.yml
  when:
    - "'download' in openwrt_action"

- name: "Make | Image"
  include_tasks: make-image.yml
  when:
    - "'build' in openwrt_action"
